#include "databasemanager.h"
#include "connection.h"
#include <QSqlQuery>
#include <QSqlError>
#include <QVariant>
#include <QDebug>
#include <QDate>

DatabaseManager::DatabaseManager(QObject *parent)
    : QObject(parent)
{
    qDebug() << "[DatabaseManager] Constructeur appelé";

    QSqlDatabase db = Connection::getInstance().getDatabase();
    if (!db.isValid() || !db.isOpen()) {
        qWarning() << "[DatabaseManager] Connexion invalide ou fermée !";
    } else {
        qDebug() << "[DatabaseManager] Connexion Oracle active.";
    }

    ensureSchema();
}

QSqlDatabase DatabaseManager::database() const
{
    return Connection::getInstance().getDatabase();
}

void DatabaseManager::ensureSchema()
{
    QSqlQuery q(database());

    // Table Residents
    if (!q.exec("CREATE TABLE residents ("
                "cin VARCHAR2(20) PRIMARY KEY, "
                "nom VARCHAR2(50), "
                "prenom VARCHAR2(50), "
                "adresse VARCHAR2(100), "
                "telephone VARCHAR2(20), "
                "email VARCHAR2(100), "
                "date_entree DATE)")) {
        if (!q.lastError().text().contains("name is already used", Qt::CaseInsensitive))
            qWarning() << "[DatabaseManager] Erreur création table residents:" << q.lastError().text();
    }

    // Table Transactions
    if (!q.exec("CREATE TABLE transactions ("
                "code VARCHAR2(20) PRIMARY KEY, "
                "type VARCHAR2(50), "
                "montant NUMBER(10,2), "
                "date_transaction DATE, "
                "description VARCHAR2(200))")) {
        if (!q.lastError().text().contains("name is already used", Qt::CaseInsensitive))
            qWarning() << "[DatabaseManager] Erreur création table transactions:" << q.lastError().text();
    }

    // Table Incidents
    if (!q.exec("CREATE TABLE incidents ("
                "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                "type VARCHAR2(50), "
                "description VARCHAR2(200), "
                "date_incident DATE, "
                "statut VARCHAR2(50))")) {
        if (!q.lastError().text().contains("name is already used", Qt::CaseInsensitive))
            qWarning() << "[DatabaseManager] Erreur création table incidents:" << q.lastError().text();
    }

    // Table Véhicules
    if (!q.exec("CREATE TABLE vehicules ("
                "id VARCHAR2(20) PRIMARY KEY, "
                "type VARCHAR2(50), "
                "capacite NUMBER, "
                "zone VARCHAR2(100), "
                "horaire VARCHAR2(50), "
                "statut VARCHAR2(50), "
                "date_ajout DATE, "
                "temps_utilise NUMBER(10,1))")) {
        if (!q.lastError().text().contains("name is already used", Qt::CaseInsensitive))
            qWarning() << "[DatabaseManager] Erreur création table vehicules:" << q.lastError().text();
    }

    qDebug() << "[DatabaseManager] Schéma vérifié ou déjà existant.";
}

////////////////////////////////////////////////////
///       RESIDENTS
////////////////////////////////////////////////////
bool DatabaseManager::addResident(const QVariantMap &data)
{
    QSqlQuery q(database());
    q.prepare("INSERT INTO residents (cin, nom, prenom, adresse, telephone, email, date_entree) "
              "VALUES (:cin, :nom, :prenom, :adresse, :telephone, :email, :date_entree)");
    q.bindValue(":cin", data["cin"]);
    q.bindValue(":nom", data["nom"]);
    q.bindValue(":prenom", data["prenom"]);
    q.bindValue(":adresse", data["adresse"]);
    q.bindValue(":telephone", data["telephone"]);
    q.bindValue(":email", data["email"]);
    q.bindValue(":date_entree", data["date_entree"]);
    return q.exec();
}

bool DatabaseManager::updateResident(const QString &cin, const QVariantMap &data)
{
    QSqlQuery q(database());
    q.prepare("UPDATE residents SET nom=:nom, prenom=:prenom, adresse=:adresse, "
              "telephone=:telephone, email=:email, date_entree=:date_entree "
              "WHERE cin=:cin");
    q.bindValue(":cin", cin);
    q.bindValue(":nom", data["nom"]);
    q.bindValue(":prenom", data["prenom"]);
    q.bindValue(":adresse", data["adresse"]);
    q.bindValue(":telephone", data["telephone"]);
    q.bindValue(":email", data["email"]);
    q.bindValue(":date_entree", data["date_entree"]);
    return q.exec();
}

bool DatabaseManager::deleteResident(const QString &cin)
{
    QSqlQuery q(database());
    q.prepare("DELETE FROM residents WHERE cin=:cin");
    q.bindValue(":cin", cin);
    return q.exec();
}

QList<QVariantMap> DatabaseManager::getAllResidents()
{
    QList<QVariantMap> list;
    QSqlQuery q("SELECT * FROM residents", database());
    while (q.next()) {
        QVariantMap m;
        m["cin"] = q.value("cin");
        m["nom"] = q.value("nom");
        m["prenom"] = q.value("prenom");
        m["adresse"] = q.value("adresse");
        m["telephone"] = q.value("telephone");
        m["email"] = q.value("email");
        m["date_entree"] = q.value("date_entree").toDate();
        list.append(m);
    }
    return list;
}

QVariantMap DatabaseManager::getResident(const QString &cin)
{
    QVariantMap m;
    QSqlQuery q(database());
    q.prepare("SELECT * FROM residents WHERE cin=:cin");
    q.bindValue(":cin", cin);
    if (q.exec() && q.next()) {
        m["cin"] = q.value("cin");
        m["nom"] = q.value("nom");
        m["prenom"] = q.value("prenom");
        m["adresse"] = q.value("adresse");
        m["telephone"] = q.value("telephone");
        m["email"] = q.value("email");
        m["date_entree"] = q.value("date_entree").toDate();
    }
    return m;
}

QList<QVariantMap> DatabaseManager::searchResidents(const QString &term)
{
    QList<QVariantMap> list;
    QSqlQuery q(database());
    q.prepare("SELECT * FROM residents WHERE nom LIKE :t OR prenom LIKE :t OR cin LIKE :t OR adresse LIKE :t OR email LIKE :t");
    q.bindValue(":t", "%" + term + "%");
    q.exec();
    while (q.next()) {
        QVariantMap m;
        m["cin"] = q.value("cin");
        m["nom"] = q.value("nom");
        m["prenom"] = q.value("prenom");
        m["adresse"] = q.value("adresse");
        m["telephone"] = q.value("telephone");
        m["email"] = q.value("email");
        m["date_entree"] = q.value("date_entree").toDate();
        list.append(m);
    }
    return list;
}

QVariantMap DatabaseManager::getStatistics()
{
    QVariantMap stats;
    QSqlQuery q(database());

    q.exec("SELECT COUNT(*) FROM residents");
    if (q.next()) stats["total"] = q.value(0);

    q.exec("SELECT COUNT(*) FROM residents WHERE date_entree >= ADD_MONTHS(SYSDATE, -12)");
    if (q.next()) stats["nouveaux_annee"] = q.value(0);

    return stats;
}

////////////////////////////////////////////////////
///       TRANSACTIONS (version corrigée)
////////////////////////////////////////////////////
bool DatabaseManager::addTransaction(const QVariantMap &data)
{
    QSqlDatabase db = database();
    QSqlQuery q(db);

    q.prepare(R"(
        INSERT INTO transactions (code_unique, type, montant, date_transaction, categorie, description)
        VALUES (:code, :type, :montant, TO_DATE(:date_transaction, 'YYYY-MM-DD'), :categorie, :description)
    )");

    q.bindValue(":code", data.value("code"));
    q.bindValue(":type", data.value("type"));
    q.bindValue(":montant", data.value("montant"));
    q.bindValue(":date_transaction", data.value("date"));  // on garde le format yyyy-MM-dd
    q.bindValue(":categorie", data.value("categorie"));
    q.bindValue(":description", data.value("description"));

    if (!q.exec()) {
        QMessageBox::critical(nullptr, "Erreur SQL",
                              "Échec de l'insertion dans Oracle :\n" + q.lastError().text());
        qWarning() << "[DatabaseManager] ❌ Erreur ajout transaction:" << q.lastError().text();
        return false;
    }

    db.commit();
    qDebug() << "[DatabaseManager] ✅ Transaction ajoutée:" << data.value("code").toString();
    return true;
}

bool DatabaseManager::updateTransaction(const QString &code, const QVariantMap &data)
{
    QSqlDatabase db = database();
    QSqlQuery q(db);

    q.prepare(R"(
        UPDATE transactions
        SET type = :type,
            montant = :montant,
            date_transaction = TO_DATE(:date_transaction, 'YYYY-MM-DD'),
            categorie = :categorie,
            description = :description
        WHERE code_unique = :code
    )");

    q.bindValue(":code", code);
    q.bindValue(":type", data.value("type"));
    q.bindValue(":montant", data.value("montant"));
    q.bindValue(":date_transaction", data.value("date"));
    q.bindValue(":categorie", data.value("categorie"));
    q.bindValue(":description", data.value("description"));

    if (!q.exec()) {
        QMessageBox::critical(nullptr, "Erreur SQL",
                              "Échec de la mise à jour :\n" + q.lastError().text());
        qWarning() << "[DatabaseManager] ❌ Erreur update transaction:" << q.lastError().text();
        return false;
    }

    db.commit();
    qDebug() << "[DatabaseManager] ✅ Transaction mise à jour:" << code;
    return true;
}

bool DatabaseManager::deleteTransaction(const QString &code)
{
    QSqlDatabase db = database();
    QSqlQuery q(db);

    q.prepare("DELETE FROM transactions WHERE code_unique = :code");
    q.bindValue(":code", code);

    if (!q.exec()) {
        QMessageBox::critical(nullptr, "Erreur SQL",
                              "Échec de la suppression :\n" + q.lastError().text());
        qWarning() << "[DatabaseManager] ❌ Erreur delete transaction:" << q.lastError().text();
        return false;
    }

    db.commit();
    qDebug() << "[DatabaseManager] 🗑 Transaction supprimée:" << code;
    return true;
}

QList<QVariantMap> DatabaseManager::getAllTransactions()
{
    QList<QVariantMap> list;
    QSqlQuery q("SELECT * FROM transactions ORDER BY date_transaction DESC", database());

    while (q.next()) {
        QVariantMap m;
        m["code"] = q.value("code_unique");
        m["type"] = q.value("type");
        m["montant"] = q.value("montant");
        m["date"] = q.value("date_transaction").toDate();
        m["categorie"] = q.value("categorie");
        m["description"] = q.value("description");
        list.append(m);
    }
    return list;
}

QVariantMap DatabaseManager::getTransaction(const QString &code)
{
    QVariantMap m;
    QSqlQuery q(database());
    q.prepare("SELECT * FROM transactions WHERE code_unique=:code");
    q.bindValue(":code", code);

    if (q.exec() && q.next()) {
        m["code"] = q.value("code_unique");
        m["type"] = q.value("type");
        m["montant"] = q.value("montant");
        m["date"] = q.value("date_transaction").toDate();
        m["categorie"] = q.value("categorie");
        m["description"] = q.value("description");
    }
    return m;
}

QList<QVariantMap> DatabaseManager::searchTransactions(const QString &term)
{
    QList<QVariantMap> list;
    QSqlQuery q(database());
    q.prepare(R"(
        SELECT * FROM transactions
        WHERE code_unique LIKE :t OR type LIKE :t OR categorie LIKE :t OR description LIKE :t
    )");

    q.bindValue(":t", "%" + term + "%");
    q.exec();

    while (q.next()) {
        QVariantMap m;
        m["code"] = q.value("code_unique");
        m["type"] = q.value("type");
        m["montant"] = q.value("montant");
        m["date"] = q.value("date_transaction").toDate();
        m["categorie"] = q.value("categorie");
        m["description"] = q.value("description");
        list.append(m);
    }
    return list;
}

////////////////////////////////////////////////////
///       INCIDENTS
////////////////////////////////////////////////////
// ========================== INCIDENTS ==========================

bool DatabaseManager::addIncident(const QVariantMap &data)
{
    QSqlQuery q(database());
    q.prepare(R"(
        INSERT INTO incidents (id, type, localisation, date_heure, niveau_gravite, statut)
        VALUES (INCIDENTS_SEQ.NEXTVAL, :type, :localisation, :date_heure, :niveau_gravite, :statut)
    )");

    q.bindValue(":type", data["type"]);
    q.bindValue(":localisation", data["localisation"]);
    q.bindValue(":date_heure", data["date_heure"]);
    q.bindValue(":niveau_gravite", data["niveau_gravite"]);
    q.bindValue(":statut", data["statut"]);

    if (!q.exec()) {
        qDebug() << "Erreur ajout incident:" << q.lastError().text();
        return false;
    }
    return true;
}

bool DatabaseManager::updateIncident(int id, const QVariantMap &data)
{
    QSqlQuery q(database());
    q.prepare(R"(
        UPDATE incidents
        SET type = :type,
            localisation = :localisation,
            date_heure = :date_heure,
            niveau_gravite = :niveau_gravite,
            statut = :statut
        WHERE id = :id
    )");

    q.bindValue(":id", id);
    q.bindValue(":type", data["type"]);
    q.bindValue(":localisation", data["localisation"]);
    q.bindValue(":date_heure", data["date_heure"]);
    q.bindValue(":niveau_gravite", data["niveau_gravite"]);
    q.bindValue(":statut", data["statut"]);

    if (!q.exec()) {
        qDebug() << "Erreur mise à jour incident:" << q.lastError().text();
        return false;
    }
    return true;
}

bool DatabaseManager::deleteIncident(int id)
{
    QSqlQuery q(database());
    q.prepare("DELETE FROM incidents WHERE id = :id");
    q.bindValue(":id", id);

    if (!q.exec()) {
        qDebug() << "Erreur suppression incident:" << q.lastError().text();
        return false;
    }
    return true;
}

QList<QVariantMap> DatabaseManager::getAllIncidents()
{
    QList<QVariantMap> list;
    QSqlQuery q("SELECT * FROM incidents ORDER BY id DESC", database());

    while (q.next()) {
        QVariantMap m;
        m["id"] = q.value("id");
        m["type"] = q.value("type");
        m["localisation"] = q.value("localisation");
        m["date_heure"] = q.value("date_heure");
        m["niveau_gravite"] = q.value("niveau_gravite");
        m["statut"] = q.value("statut");
        list.append(m);
    }
    return list;
}

QVariantMap DatabaseManager::getIncident(int id)
{
    QVariantMap m;
    QSqlQuery q(database());
    q.prepare("SELECT * FROM incidents WHERE id = :id");
    q.bindValue(":id", id);

    if (q.exec() && q.next()) {
        m["id"] = q.value("id");
        m["type"] = q.value("type");
        m["localisation"] = q.value("localisation");
        m["date_heure"] = q.value("date_heure");
        m["niveau_gravite"] = q.value("niveau_gravite");
        m["statut"] = q.value("statut");
    }
    return m;
}

QList<QVariantMap> DatabaseManager::searchIncidents(const QString &term)
{
    QList<QVariantMap> list;
    QSqlQuery q(database());
    q.prepare(R"(
        SELECT * FROM incidents
        WHERE LOWER(type) LIKE LOWER(:t)
           OR LOWER(localisation) LIKE LOWER(:t)
           OR LOWER(statut) LIKE LOWER(:t)
        ORDER BY id DESC
    )");
    q.bindValue(":t", "%" + term + "%");
    q.exec();

    while (q.next()) {
        QVariantMap m;
        m["id"] = q.value("id");
        m["type"] = q.value("type");
        m["localisation"] = q.value("localisation");
        m["date_heure"] = q.value("date_heure");
        m["niveau_gravite"] = q.value("niveau_gravite");
        m["statut"] = q.value("statut");
        list.append(m);
    }
    return list;
}
QVariantMap DatabaseManager::getIncidentStatistics()
{
    QVariantMap stats;
    QSqlQuery q(database());

    // Total d'incidents
    q.exec("SELECT COUNT(*) FROM incidents");
    if (q.next()) stats["total"] = q.value(0);

    // Incidents en attente
    q.exec("SELECT COUNT(*) FROM incidents WHERE statut = 'En Attente'");
    if (q.next()) stats["en_attente"] = q.value(0);

    // Incidents en cours
    q.exec("SELECT COUNT(*) FROM incidents WHERE statut = 'En Cours'");
    if (q.next()) stats["en_cours"] = q.value(0);

    // Incidents traités
    q.exec("SELECT COUNT(*) FROM incidents WHERE statut = 'Traité'");
    if (q.next()) stats["traite"] = q.value(0);

    return stats;
}



////////////////////////////////////////////////////
///       VEHICULES
////////////////////////////////////////////////////
bool DatabaseManager::addVehicule(const QVariantMap &data)
{
    QSqlQuery q(database());
    q.prepare("INSERT INTO vehicules (id, type, capacite, zone, horaire, statut, date_ajout, temps_utilise) "
              "VALUES (:id, :type, :capacite, :zone, :horaire, :statut, :date_ajout, :temps_utilise)");

    q.bindValue(":id", data["id"]);
    q.bindValue(":type", data["type"]);
    q.bindValue(":capacite", data["capacite"]);
    q.bindValue(":zone", data["zone"]);
    q.bindValue(":horaire", data["horaire"]);
    q.bindValue(":statut", data["statut"]);

    QString dateAjout = data["date_ajout"].toString();
    if (dateAjout.isEmpty())
        dateAjout = QDateTime::currentDateTime().toString("yyyy-MM-dd hh:mm:ss");

    q.bindValue(":date_ajout", dateAjout);
    q.bindValue(":temps_utilise", data["temps_utilise"]);

    if(!q.exec())
    {
        qDebug() << "Erreur SQL:" << q.lastError().text();
        return false;
    }
    return true;
}


bool DatabaseManager::updateVehicule(const QString &id, const QVariantMap &data)
{
    QSqlQuery q(database());
    q.prepare("UPDATE vehicules SET type=:type, capacite=:capacite, zone=:zone, horaire=:horaire, statut=:statut, date_ajout=:date_ajout, temps_utilise=:temps_utilise WHERE id=:id");
    q.bindValue(":id", id);
    q.bindValue(":type", data["type"]);
    q.bindValue(":capacite", data["capacite"]);
    q.bindValue(":zone", data["zone"]);
    q.bindValue(":horaire", data["horaire"]);
    q.bindValue(":statut", data["statut"]);
    q.bindValue(":date_ajout", data["date_ajout"]);
    q.bindValue(":temps_utilise", data["temps_utilise"]);
    return q.exec();
}

bool DatabaseManager::deleteVehicule(const QString &id)
{
    QSqlQuery q(database());
    q.prepare("DELETE FROM vehicules WHERE id=:id");
    q.bindValue(":id", id);
    return q.exec();
}

QList<QVariantMap> DatabaseManager::getAllVehicules()
{
    QList<QVariantMap> list;
    QSqlQuery q("SELECT * FROM vehicules", database());

    while (q.next()) {
        QVariantMap m;
        m["id"] = q.value("ID");
        m["type"] = q.value("TYPE");
        m["capacite"] = q.value("CAPACITE");
        m["zone"] = q.value("ZONE");
        m["horaire"] = q.value("HORAIRE");
        m["statut"] = q.value("STATUT");
        m["date_ajout"] = q.value("DATE_AJOUT").toString();  // ✅ affichage correct
        m["temps_utilise"] = q.value("TEMPS_UTILISE");
        list.append(m);
    }
    return list;
}

QVariantMap DatabaseManager::getVehicule(const QString &id)
{
    QVariantMap m;
    QSqlQuery q(database());
    q.prepare("SELECT * FROM vehicules WHERE id=:id");
    q.bindValue(":id", id);
    if (q.exec() && q.next()) {
        m["id"] = q.value("ID");
        m["type"] = q.value("TYPE");
        m["capacite"] = q.value("CAPACITE");
        m["zone"] = q.value("ZONE");
        m["horaire"] = q.value("HORAIRE");
        m["statut"] = q.value("STATUT");
        m["date_ajout"] = q.value("DATE_AJOUT").toString();  // ✅ affichage correct
        m["temps_utilise"] = q.value("TEMPS_UTILISE");
    }
    return m;
}

QList<QVariantMap> DatabaseManager::searchVehicules(const QString &term)
{
    QList<QVariantMap> list;
    QSqlQuery q(database());
    q.prepare("SELECT * FROM vehicules WHERE id LIKE :t OR type LIKE :t OR zone LIKE :t OR statut LIKE :t");
    q.bindValue(":t", "%" + term + "%");
    q.exec();
    while (q.next()) {
        QVariantMap m;
        m["id"] = q.value("ID");
        m["type"] = q.value("TYPE");
        m["capacite"] = q.value("CAPACITE");
        m["zone"] = q.value("ZONE");
        m["horaire"] = q.value("HORAIRE");
        m["statut"] = q.value("STATUT");
        m["date_ajout"] = q.value("DATE_AJOUT").toString();  // ✅ affichage correct
        m["temps_utilise"] = q.value("TEMPS_UTILISE");
        list.append(m);
    }
    return list;
}
