#!/bin/bash
# Script de test du système RFID Smart City
# Usage: ./test_rfid.sh

echo "======================================="
echo "TEST SYSTÈME RFID SMART CITY"
echo "======================================="
echo ""
echo "SCÉNARIOS DE TEST:"
echo ""
echo "1. Accès APPROUVÉ (Carte autorisée)"
echo "   UID:8F6720C5"
echo "   APPROVED:8F6720C5"
echo ""
echo "2. Tentatives REFUSÉES (3x DENIED = Incident)"
echo "   UID:UNAUTHORIZED01"
echo "   DENIED:UNAUTHORIZED01"
echo "   DENIED:UNAUTHORIZED01"  
echo "   DENIED:UNAUTHORIZED01"
echo "   → Incident automatique créé"
echo ""
echo "3. Panne Ascenseur"
echo "   PANNE:8F6720C5"
echo ""
echo "======================================="
echo ""
echo "RÉSULTATS ATTENDUS:"
echo "✅ Carte autorisée → Accès accordé"
echo "❌ 3 tentatives refusées → Incident de sécurité"
echo "🔧 Panne → Incident de panne d'ascenseur"
echo ""
echo "Pour simuler dans l'application:"
echo "- Dans la page Incidents"
echo "- Utilisez le bouton 'Simuler' ou entrez les messages directement"
echo ""
