-- Script de verification des incidents RFID
-- Lance cette requete dans SQL*Plus ou SQL Developer

SET HEADING ON
SET FEEDBACK ON
SET PAGESIZE 50
SET LINESIZE 150

COLUMN ID_INCIDENT FORMAT 9999
COLUMN TYPE_INCIDENT FORMAT A30
COLUMN NIVEAU_GRAVITE FORMAT 99
COLUMN DATE_INCIDENT FORMAT A20
COLUMN DESCRIPTION FORMAT A50
COLUMN STATUS FORMAT A15

PROMPT ========================================
PROMPT Test RFID - Verification des Incidents
PROMPT ========================================
PROMPT

-- Afficher les incidents crees dans les 5 dernieres minutes
PROMPT [1] Derniers incidents RFID (5 dernieres minutes):
PROMPT

SELECT 
    ID_INCIDENT,
    TYPE_INCIDENT,
    NIVEAU_GRAVITE,
    TO_CHAR(DATE_INCIDENT, 'DD/MM/YYYY HH24:MI:SS') AS DATE_INCIDENT,
    SUBSTR(DESCRIPTION, 1, 40) AS DESCRIPTION,
    STATUT AS STATUS
FROM INCIDENTS
WHERE DATE_INCIDENT > TRUNC(SYSDATE) + (SYSDATE - 5/24/60)
ORDER BY DATE_INCIDENT DESC;

PROMPT
PROMPT [2] Tous les incidents de type "Tentative d'acces non autorise":
PROMPT

SELECT 
    ID_INCIDENT,
    TYPE_INCIDENT,
    NIVEAU_GRAVITE,
    TO_CHAR(DATE_INCIDENT, 'DD/MM/YYYY HH24:MI:SS') AS DATE_INCIDENT,
    ID_RESIDENT
FROM INCIDENTS
WHERE TYPE_INCIDENT LIKE '%acces%' OR TYPE_INCIDENT LIKE '%autorise%'
ORDER BY DATE_INCIDENT DESC;

PROMPT
PROMPT [3] Statistiques:
PROMPT

SELECT 
    COUNT(*) AS TOTAL_INCIDENTS,
    SUM(CASE WHEN NIVEAU_GRAVITE = 3 THEN 1 ELSE 0 END) AS INCIDENTS_SEVERITE_3,
    SUM(CASE WHEN STATUT = 'EN ATTENTE' THEN 1 ELSE 0 END) AS INCIDENTS_EN_ATTENTE
FROM INCIDENTS
WHERE DATE_INCIDENT > TRUNC(SYSDATE);

PROMPT
PROMPT ========================================
PROMPT Verification terminee
PROMPT ========================================
